### ISSUE TITLE
Hand issue 20/07/16

### ISSUE THREAD

**Issue by McHox** [BruceKnowsHow/Ebin-Shaders#3]
buggy hand in latest
![2016-07-20_01 33 18](https://cloud.githubusercontent.com/assets/9086820/16970110/132677f4-4e1a-11e6-8932-431ee08b8d17.png)

**Comment by dotModded** [comment]
I'm aware, I know how to fix it however bruce insists that I don't for now.

**Comment by McHox** [comment]
alright

**Comment by BruceKnowsHow** [comment]
I've avoided fixing it up until this point because it would require using another buffer, which I really do not want to do if I don't have to. I'm hoping [this issue](https://github.com/sp614x/optifine/issues/195) sorts itself out so that I can fix it elegantly.

I will fix it closer to release if OptiLad still hasn't acted.

**Comment by BruceKnowsHow** [comment]
OptiLad hasn't acted yet. I realized the volumetric fog buffer wasn't necessary at the moment, as volumetric fog is not active and will not be for a while. I used the VL buffer to fix this issue, for the time being at least.

Let's hope that one of the fixes listed [here](https://github.com/BruceKnowsHow/Ebin-Shaders/commit/e53cec34afeabaca2b876d4a8b73e947ab9bc1af) is implemented, so that VL can be re-added in the future.
